<?php
$auto_reviews_en = array(
    array("name" => "Zvonko E.", "text" => "Culoarea ramane intensa chiar si dupa multe spalari."),
    array("name" => "Marijan H.", "text" => "Tricoul NORIKS m-a surprins placut. Materialul este moale pe piele si croiala sta foarte bine."),
    array("name" => "Tin V.", "text" => "Arata modern si premium, desi pretul este foarte corect."),
    array("name" => "Deni B.", "text" => "Il port aproape zilnic si inca arata foarte bine."),
    array("name" => "Kristijan L.", "text" => "La inceput am fost sceptic, dar dupa prima purtare am comandat inca unul."),
    array("name" => "Vjeko I.", "text" => "Design simplu, usor de combinat cu orice."),
    array("name" => "Hrvoje S.", "text" => "Dupa multe spalari inca arata ca nou."),
    array("name" => "Niksa H.", "text" => "Nu se vede transpiratia si materialul respira foarte bine."),
    array("name" => "Marko U.", "text" => "Se potriveste bine atat persoanelor mai slabe, cat si celor mai robuste."),
    array("name" => "Andro P.", "text" => "Pentru mine a devenit tricoul de baza. Este confortabil, rezistent si marimea corespunde perfect."),
    array("name" => "Matija K.", "text" => "Material usor, dar deloc transparent."),
    array("name" => "Dario Z.", "text" => "Foarte confortabil. L-am purtat la birou si in oras, se potriveste perfect."),
    array("name" => "Lovro I.", "text" => "Merge bine cu orice culoare si orice pantaloni."),
    array("name" => "Ivan L.", "text" => "Este suficient de lung si ramane bine asezat toata ziua."),
    array("name" => "Blaz H.", "text" => "Nu irita pielea nici atunci cand este foarte cald."),
    array("name" => "Toni J.", "text" => "Bun si pentru sport, si pentru tinute casual."),
    array("name" => "Zoran G.", "text" => "Material placut la atingere si foarte rezistent."),
    array("name" => "Stjepan T.", "text" => "Se vede imediat ca nu este un tricou ieftin."),
    array("name" => "Boris C.", "text" => "Simplu, curat si foarte bine croit."),
    array("name" => "Danijel P.", "text" => "Am primit mai mult decat ma asteptam de la acest produs."),
    array("name" => "Mislav U.", "text" => "L-am luat in calatorie si aproape ca nu s-a sifonat."),
    array("name" => "Ivan R.", "text" => "Foarte usor si comod la purtare."),
    array("name" => "Tomislav L.", "text" => "Il port si cu sacou, si cu haine sport."),
    array("name" => "Nikola O.", "text" => "Culoarea ramane constanta si dupa multe purtari."),
    array("name" => "Mario M.", "text" => "Are o senzatie premium chiar de la prima atingere."),
    array("name" => "Robert L.", "text" => "Arata foarte bine pe corp si da un aspect ingrijit."),
    array("name" => "Ante J.", "text" => "A intrat imediat in rotatia mea zilnica."),
    array("name" => "Nikola T.", "text" => "Moale ca bumbacul, dar pare mai rezistent."),
    array("name" => "Filip P.", "text" => "Respira bine si nu se lipeste de piele. Croiala sta excelent."),
    array("name" => "Damir V.", "text" => "Dupa mai multe spalari nu si-a pierdut forma si nici culoarea."),
);
?>
