<?php
$auto_reviews_en = array(
    array("name" => "Jure M.", "text" => "Culoarea ramane la fel chiar si dupa multe spalari."),
    array("name" => "Roko P.", "text" => "Boxerii NORIKS sunt foarte comozi. Materialul este moale si nu strange deloc."),
    array("name" => "Marko S.", "text" => "Foarte confortabili pentru toata ziua, aproape ca nu ii simt."),
    array("name" => "Tomo R.", "text" => "Elasticul este ferm, dar nu strange si nu lasa urme pe piele."),
    array("name" => "Josip D.", "text" => "Usori si aerisiti, perfecti pentru serviciu si sala."),
    array("name" => "Luka M.", "text" => "Isi pastreaza foarte bine forma si dupa multe spalari."),
    array("name" => "Kristijan C.", "text" => "Material neted, fara cusaturi care sa deranjeze."),
    array("name" => "Davor V.", "text" => "Dupa o zi intreaga totul ramane la locul lui, fara sa se ridice."),
    array("name" => "Mislav L.", "text" => "Par de calitate inca din primul moment in care ii atingi."),
    array("name" => "Petar G.", "text" => "Ii port de saptamani si materialul inca arata impecabil."),
    array("name" => "Ante B.", "text" => "Croiala perfecta, urmeaza corpul fara sa stranga."),
    array("name" => "Filip J.", "text" => "Cracii nu se ridica, ceea ce pentru mine este un mare plus."),
    array("name" => "Nikola R.", "text" => "Au devenit prima alegere din sertar."),
    array("name" => "Matija S.", "text" => "Fara transpiratie neplacuta, materialul respira foarte bine."),
    array("name" => "Ivan H.", "text" => "Raport excelent intre pret si calitate."),
    array("name" => "Branimir N.", "text" => "Se aseaza bine chiar daca sunt intre doua marimi."),
    array("name" => "Andrej M.", "text" => "Ideali si pentru serviciu, si pentru antrenamente."),
    array("name" => "Darko Z.", "text" => "Materialul se usuca repede, foarte buni pentru calatorii."),
    array("name" => "Vedran M.", "text" => "Perfecti pentru vara, nu se lipesc de piele."),
    array("name" => "Boris R.", "text" => "Atat de confortabili incat aproape nu ii simt."),
    array("name" => "Karol D.", "text" => "Ii port la sala si la birou fara nicio problema."),
    array("name" => "Zlatko R.", "text" => "Foarte bine croiti pentru o constitutie mai puternica."),
    array("name" => "Tomislav E.", "text" => "Fac fata foarte bine si unei zile active, si unui antrenament."),
    array("name" => "Mario L.", "text" => "Foarte comozi chiar si cand sunt in miscare toata ziua."),
    array("name" => "Zeljko K.", "text" => "Nu scriu des recenzii, dar boxerii acestia chiar merita."),
    array("name" => "Oleg T.", "text" => "Materialul este atat de moale incat aproape nu se simte."),
    array("name" => "Karlo H.", "text" => "Elastic excelent, nu se ruleaza si nu deranjeaza."),
    array("name" => "Augustin J.", "text" => "Au devenit rapid optiunea mea preferata."),
    array("name" => "Benedikt K.", "text" => "In sfarsit boxeri care nu strang."),
    array("name" => "Zdravko T.", "text" => "Boxeri care chiar au sens pentru purtare zilnica."),
);
?>
