<?php
$auto_reviews_en = array(
    array("name" => "Zdeněk E.", "text" => "Barva zůstává stejná i po mnoha praních."),
    array("name" => "Marian H.", "text" => "Tričko Noriks mě opravdu překvapilo. Materiál je příjemný na kůži a střih kopíruje postavu bez stahování. I po celém dni nošení působí svěže."),
    array("name" => "Tomáš V.", "text" => "Vypadá moderně a luxusně, i když je cena velmi dostupná."),
    array("name" => "Denis B.", "text" => "Nosím ho každý den."),
    array("name" => "Kristián L.", "text" => "Zpočátku jsem si nebyl jistý, ale předčilo to moje očekávání. Koupím si další."),
    array("name" => "Viktor I.", "text" => "Minimalistický design, hodí se ke všemu."),
    array("name" => "Radek S.", "text" => "Po deseti praních stále jako nové."),
    array("name" => "Nikolas H.", "text" => "Není vidět pot."),
    array("name" => "Martin U.", "text" => "Sedí jak štíhlým, tak i silnějším postavám."),
    array("name" => "Ondřej P.", "text" => "Noriks se stal mým každodenním standardem. Měkké, ale pevné a drží tvar. Velikost odpovídá tabulce."),
    array("name" => "Matěj K.", "text" => "Materiál je lehký, ale neprůhledný."),
    array("name" => "David Z.", "text" => "Velmi pohodlné tričko. Už jsem objednal další. Hodí se téměř ke všemu."),
    array("name" => "Lukáš I.", "text" => "Hodí se ke všem barvám."),
    array("name" => "Jan L.", "text" => "Dostatečně dlouhé, aby zůstalo v kalhotách."),
    array("name" => "Blažej H.", "text" => "Materiál nedráždí pokožku ani při pocení."),
    array("name" => "Tony J.", "text" => "Na sport i do města."),
    array("name" => "Zoran G.", "text" => "Měkký, ale odolný materiál."),
    array("name" => "Štěpán T.", "text" => "Na první pohled je vidět kvalita."),
    array("name" => "Boris C.", "text" => "Jednoduché, ale moderní."),
    array("name" => "Daniel P.", "text" => "Dostal jsem víc, než jsem čekal."),
    array("name" => "Michal U.", "text" => "Měl jsem ho na cestách – nemačkalo se ani po hodinách v kufru."),
    array("name" => "Jan R.", "text" => "Super lehké a pohodlné."),
    array("name" => "Tomáš L.", "text" => "Nosím ho jak k saku, tak k teplákům."),
    array("name" => "Nikola O.", "text" => "Stálobarevné."),
    array("name" => "Martin E.", "text" => "Mám jich už pět."),
    array("name" => "Goran T.", "text" => "Skvělý vzhled i funkčnost."),
    array("name" => "Mario M.", "text" => "Na dotek působí prémiově."),
    array("name" => "Robert L.", "text" => "Vypadá mužně a elegantně."),
    array("name" => "Antonín J.", "text" => "Nosím ho skoro obden – pořád v rotaci."),
    array("name" => "Nikola T.", "text" => "Měkké jako bavlna, ale odolnější."),
    array("name" => "Alan M.", "text" => "Materiál je měkký, ale nevytahuje se ani po více praních."),
    array("name" => "Filip P.", "text" => "Noriks mě dostal už při prvním nošení. Prodyšné a nepřiléhá na kůži."),
    array("name" => "Bruno L.", "text" => "Ideální délka rukávů."),
    array("name" => "Gordon F.", "text" => "Dlouho jsem hledal takový model. Díky!"),
    array("name" => "Kristián B.", "text" => "Velmi odolné — po mnoha nošeních pořád jako nové."),
    array("name" => "Tomáš T.", "text" => "Luxusní na dotek."),
    array("name" => "Petr N.", "text" => "Skvěle vypadá s bundou."),
    array("name" => "David V.", "text" => "Po několika praních žádné známky opotřebení. Koupím další."),
    array("name" => "Igor N.", "text" => "Nemačká se ani po celém dni."),
    array("name" => "Norbert U.", "text" => "Barva vypadá ještě lépe naživo."),
    array("name" => "Sven Z.", "text" => "Snadno se žehlí."),
    array("name" => "Zdeněk Z.", "text" => "Jsem nadšený! Splnilo vše, co jsem hledal."),
    array("name" => "Adrian L.", "text" => "Hodí se ke všem kalhotám."),
    array("name" => "Antonín F.", "text" => "Sedí i když jsem mezi velikostmi."),
    array("name" => "Jan K.", "text" => "Perfektní velikost."),
    array("name" => "Žaneta G.", "text" => "Ideální tričko pro moderního muže."),
    array("name" => "Dominik M.", "text" => "Klasika s nádechem stylu."),
    array("name" => "Radim A.", "text" => "Sportovní styl s elegantním zakončením."),
    array("name" => "Mario H.", "text" => "Do kanceláře i na volný čas."),
    array("name" => "Lukáš I.", "text" => "Netáhne v podpaží."),
    array("name" => "Jan M.", "text" => "Střih perfektní i pro vyšší postavu."),
    array("name" => "Štěpán K.", "text" => "Našel jsem nové oblíbené tričko."),
    array("name" => "Bohdan S.", "text" => "Ideální na cestování – lehké a skladné."),
    array("name" => "František C.", "text" => "Měl jsem ho na pohovoru – cítil jsem se sebevědomě."),
    array("name" => "Tomáš H.", "text" => "Perfektní délka i střih."),
    array("name" => "Nikola G.", "text" => "Nosím ho do práce i do města."),
    array("name" => "Vladimír G.", "text" => "Elegantní a pohodlné."),
    array("name" => "Josef L.", "text" => "Ideální rovnováha mezi elegancí a pohodlím."),
    array("name" => "Lukáš T.", "text" => "Skvělé na trénink i běžné nošení."),
    array("name" => "Jan J.", "text" => "Kvalita nad cenou."),
    array("name" => "Leon Z.", "text" => "Drží tvar i barvu."),
    array("name" => "Blažej E.", "text" => "Dá se snadno upravit do formálnějšího stylu."),
    array("name" => "Martin T.", "text" => "Dostal jsem spoustu komplimentů."),
    array("name" => "Kristián H.", "text" => "Nechytá chlupy."),
    array("name" => "Tibor V.", "text" => "Drží celý den."),
    array("name" => "Filip Z.", "text" => "Tričko pro každou příležitost."),
    array("name" => "Radek V.", "text" => "Pohodlné po celý den."),
    array("name" => "Mirek D.", "text" => "Minimalistický a mužný design."),
    array("name" => "Saša O.", "text" => "Funguje každý den."),
    array("name" => "Robert G.", "text" => "Nejlepší nákup online."),
    array("name" => "Antonín G.", "text" => "Moje první volba každé ráno."),
    array("name" => "David L.", "text" => "Sedí jako ulité."),
    array("name" => "Kristián V.", "text" => "Střih je opravdu perfektní — drží linii bez stahování."),
    array("name" => "Alan W.", "text" => "Vypadá dražší, než ve skutečnosti je."),
    array("name" => "Emil W.", "text" => "Působí luxusně."),
    array("name" => "Václav U.", "text" => "Materiál je měkký, ale nejeví známky opotřebení."),
    array("name" => "Tibor E.", "text" => "Rukávy nejsou příliš úzké."),
    array("name" => "Petr M.", "text" => "Dlouho jsem nebyl tak spokojený s obyčejným tričkem."),
    array("name" => "Dominik T.", "text" => "Na procházky i večerní výlety."),
    array("name" => "Bruno K.", "text" => "Nedeformuje se."),
    array("name" => "Antonín I.", "text" => "Nejpohodlnější tričko této sezóny."),
    array("name" => "Siniša P.", "text" => "Rychle schne."),
    array("name" => "Karel U.", "text" => "Casual styl, který mám rád."),
    array("name" => "Nikolas Z.", "text" => "Skvělý poměr ceny a kvality."),
    array("name" => "Fabian R.", "text" => "Málo se mačká — ideální."),
    array("name" => "Zlatko F.", "text" => "Konečně moderní tričko bez oběti pohodlí."),
    array("name" => "Martin P.", "text" => "Doporučuji všemi deseti."),
    array("name" => "Josef X.", "text" => "Lehké na léto, ideální na vrstvení."),
    array("name" => "Vladimír K.", "text" => "Stalo se mým oblíbeným."),
    array("name" => "Erik J.", "text" => "Naživo ještě lepší než na fotkách."),
    array("name" => "Tomáš S.", "text" => "Speciální vzhled i pocit."),
    array("name" => "Karel Z.", "text" => "Stejně dobré i pod svetrem."),
    array("name" => "Zbyněk N.", "text" => "Nesklouzává z ramen."),
    array("name" => "Jan D.", "text" => "Pohodlné a profesionální."),
    array("name" => "Nino G.", "text" => "Zůstává svěží celý den."),
    array("name" => "Lukáš M.", "text" => "Konečně tričko i pro vyšší postavy."),
    array("name" => "Boris T.", "text" => "Tak pohodlné, že je jako pyžamo."),
    array("name" => "Filip K.", "text" => "Ideální délka – nevylézá z kalhot."),
    array("name" => "Tomáš J.", "text" => "Rychle schne – ideální na cesty."),
    array("name" => "Štěpán M.", "text" => "Skvělé nejen vzhledem, ale i pocitem."),
    array("name" => "Goran V.", "text" => "Pokud hledáte kvalitu — tohle je ono."),
    array("name" => "David I.", "text" => "Praktické a moderní."),
    array("name" => "Željko B.", "text" => "Každý outfit vypadá lépe."),
    array("name" => "Neven D.", "text" => "Pět z pěti i od přítelkyně."),
    array("name" => "Vědran G.", "text" => "Po každém praní jako nové."),
    array("name" => "Jan Z.", "text" => "Součást mého každodenního outfitu."),
    array("name" => "Kristián D.", "text" => "Perfektní rovnováha sportu a elegance."),
    array("name" => "Michal R.", "text" => "Drží tvar i barvu."),
    array("name" => "Matěj V.", "text" => "Sedí perfektně ve všech směrech."),
    array("name" => "Filip F.", "text" => "Nemění tvar po praní."),
    array("name" => "Alan C.", "text" => "Barva vydrží i po mnoha cyklech."),
    array("name" => "Kristián P.", "text" => "Střih kopíruje postavu bez nepohodlí."),
    array("name" => "Blažej K.", "text" => "Sedí i silnější postavě."),
    array("name" => "Tomáš G.", "text" => "Odolné i po sportu."),
    array("name" => "Andrej N.", "text" => "Prodyšné i během náročného dne."),
    array("name" => "Antonín K.", "text" => "Materiál působí opravdu kvalitně."),
    array("name" => "Saša R.", "text" => "Zvládlo 12 hodin v práci."),
    array("name" => "Jan N.", "text" => "Takové tričko jsem hledal roky."),
    array("name" => "Dominik R.", "text" => "Hodí se ke všemu."),
    array("name" => "Lukáš W.", "text" => "Skvělá alternativa ke košili."),
    array("name" => "Emil T.", "text" => "Ideální řešení na každý den."),
    array("name" => "Robert N.", "text" => "Drží kvalitu i po měsíci praní."),
    array("name" => "Martin Q.", "text" => "Žádné nepohodlí ani po celém dni."),
    array("name" => "Kristián J.", "text" => "Do práce i na volný čas."),
    array("name" => "Josef E.", "text" => "Sedí perfektně."),
    array("name" => "Željko F.", "text" => "I po opakovaném nošení jako nové."),
    array("name" => "David W.", "text" => "Pohodlné v každé poloze."),
    array("name" => "Lukáš B.", "text" => "Nosím ho denně."),
    array("name" => "Karel D.", "text" => "Vypadá jako šité na míru."),
    array("name" => "Siniša G.", "text" => "Skvělé i při pocení."),
    array("name" => "Branimír V.", "text" => "Nevytahuje se po praní."),
    array("name" => "Damjan S.", "text" => "Ideální na vrstvení."),
    array("name" => "Antonín V.", "text" => "Svěží celý den."),
    array("name" => "Tony L.", "text" => "Příjemné i na slunci."),
    array("name" => "Nikola L.", "text" => "Spousta komplimentů."),
    array("name" => "Boris M.", "text" => "Výjimečný produkt — musel jsem napsat recenzi."),
    array("name" => "Marian K.", "text" => "Snadná údržba, rychlé schnutí."),
    array("name" => "Goran S.", "text" => "Detaily u krku jsou velmi kvalitní."),
    array("name" => "Bruno G.", "text" => "Působí, jako by vydrželo roky."),
    array("name" => "Václav C.", "text" => "Lichotí postavě a není průhledné."),
    array("name" => "Filip O.", "text" => "Skvělá služba."),
    array("name" => "Zdeněk D.", "text" => "Koupil jsem jedno a hned objednal další tři."),
    array("name" => "Tomáš P.", "text" => "Pohodlné celý den."),
    array("name" => "Štěpán P.", "text" => "Dostatečně pružné."),
    array("name" => "Michal S.", "text" => "Kvalitní zpracování."),
    array("name" => "Viktor I.", "text" => "Nepřiléhá ani při pocení."),
    array("name" => "Antonín R.", "text" => "Jednoduše dokonalé."),
    array("name" => "Lukáš R.", "text" => "Nejpohodlnější tričko, co mám."),
    array("name" => "Nikola A.", "text" => "Skvělé i v zimě pod mikinou."),
    array("name" => "Radek E.", "text" => "Recenze nelhaly."),
    array("name" => "Andrej J.", "text" => "Skvělá investice."),
    array("name" => "David H.", "text" => "Perfektní střih a komfort."),
    array("name" => "Blažej P.", "text" => "Vše na jedničku."),
    array("name" => "Miroslav Z.", "text" => "Díky střihu vypadám upraveněji."),
    array("name" => "Filip B.", "text" => "Nejlepší přizpůsobení tělu."),
    array("name" => "Kristián E.", "text" => "Příjemné na kůži, žádné stopy."),
    array("name" => "Marin D.", "text" => "Nechytá prach ani chlupy."),
    array("name" => "Jan D.", "text" => "Ideální pro každého, kdo chce pohodlí i styl."),
    array("name" => "Karel N.", "text" => "Ani na slunci nebylo horko."),
    array("name" => "Mario K.", "text" => "Moderní, ale ne přehnané."),
    array("name" => "Željko E.", "text" => "Vše odpovídá realitě."),
    array("name" => "Siniša H.", "text" => "Čistý a jednoduchý vzhled."),
    array("name" => "Damjan V.", "text" => "Do práce i večer ven."),
    array("name" => "Bořivoj J.", "text" => "Žádná loga, jen styl."),
    array("name" => "Daniel K.", "text" => "Minimalismus, který funguje."),
    array("name" => "Jakub P.", "text" => "Objednal jsem další dvě."),
    array("name" => "Leon F.", "text" => "Lehký lesk působí elegantně."),
    array("name" => "Gordon J.", "text" => "Střih zvýrazňuje postavu."),
    array("name" => "Václav R.", "text" => "Dlouho jsem nebyl tak spokojen."),
    array("name" => "Tibor B.", "text" => "Perfektní na každý den."),
    array("name" => "Michal K.", "text" => "Velmi příjemné na kůži."),
    array("name" => "Ondřej V.", "text" => "Stálá kvalita každý týden."),
    array("name" => "David C.", "text" => "Opravdu stojí za to."),
    array("name" => "Tomáš N.", "text" => "Zvládne i sušičku."),
    array("name" => "Boris U.", "text" => "Mám ho ve více barvách."),
    array("name" => "Alan T.", "text" => "Wow efekt hned napoprvé."),
    array("name" => "Štěpán H.", "text" => "Límec drží perfektně."),
    array("name" => "Dominik E.", "text" => "Nejlepší tričko, co jsem kdy měl."),
    array("name" => "Antonín H.", "text" => "Přesně to, co jsem hledal."),
    array("name" => "Filip L.", "text" => "Výborné zpracování."),
    array("name" => "Kristián T.", "text" => "Lehké, ale odolné."),
    array("name" => "Marian O.", "text" => "Pocit volnosti."),
    array("name" => "Petr B.", "text" => "Skvělé i při vlhku."),
    array("name" => "František D.", "text" => "Koupil jsem více kusů."),
    array("name" => "Nikola M.", "text" => "Pružné a pohodlné."),
    array("name" => "Jan R.", "text" => "Funguje v létě i zimě."),
    array("name" => "Mario F.", "text" => "Vypadá profesionálně."),
    array("name" => "Željko C.", "text" => "Vydrží i náročné nošení."),
    array("name" => "Vladimír F.", "text" => "Drží tvar i po mnoha praních."),
    array("name" => "Antonín J.", "text" => "Lepší než drahé značky."),
    array("name" => "Lukáš V.", "text" => "Zůstává pevné celý den."),
    array("name" => "Nikolas V.", "text" => "Po měsících stále jako nové."),
    array("name" => "Kristián N.", "text" => "Perfektní hustota materiálu."),
    array("name" => "Bořivoj C.", "text" => "Sedlo hned napoprvé."),
    array("name" => "Zdeněk U.", "text" => "Perfektní délka i ramena."),
    array("name" => "Michal S.", "text" => "Velmi spokojen."),
    array("name" => "Goran J.", "text" => "Minimalismus, který funguje."),
    array("name" => "Krešimir Y.", "text" => "Cítím se sebevědomě."),
    array("name" => "Vědran F.", "text" => "Perfektní každodenní tričko."),
    array("name" => "David O.", "text" => "Příjemné překvapení."),
    array("name" => "Nikola H.", "text" => "Límec drží i po sušičce."),
    array("name" => "Tibor G.", "text" => "Určitě koupím znovu."),
    array("name" => "Angelo M.", "text" => "Textura je skvělá."),
    array("name" => "Žarko T.", "text" => "Rychlé doručení."),
    array("name" => "Nikola J.", "text" => "Perfektní v ramenou."),
    array("name" => "Andrej P.", "text" => "Nejlepší poměr ceny a kvality."),
    array("name" => "Alan J.", "text" => "Jako šité na míru."),
    array("name" => "Vladimír C.", "text" => "Rychlé doručení, perfektní balení."),
    array("name" => "David I.", "text" => "Na sobotu i večeři."),
    array("name" => "Karel M.", "text" => "Bez podráždění pokožky."),
    array("name" => "František P.", "text" => "Bez zápachu i po celém dni."),
    array("name" => "Zoran L.", "text" => "Opticky lepší postava."),
    array("name" => "Igor S.", "text" => "Jednoduchá objednávka."),
    array("name" => "Antonín D.", "text" => "Beru další barvu."),
    array("name" => "Andrej K.", "text" => "Cítím se v něm lépe."),
    array("name" => "Michal N.", "text" => "Bez nutnosti žehlení."),
    array("name" => "Goran P.", "text" => "Měkké švy."),
    array("name" => "Jan G.", "text" => "Ideální do kanceláře."),
    array("name" => "Leo C.", "text" => "Barva odpovídá fotkám."),
    array("name" => "Damjan P.", "text" => "Vypadá dražší."),
    array("name" => "Ervin S.", "text" => "Měkké a pevné."),
    array("name" => "Václav M.", "text" => "Odolné i při častém nošení."),
    array("name" => "Nikola V.", "text" => "Materiál odpuzuje skvrny."),
    array("name" => "Štěpán O.", "text" => "XL sedí perfektně."),
    array("name" => "Boris R.", "text" => "Čisté linie."),
    array("name" => "Antonín Š.", "text" => "Od fitka po kavárnu."),
    array("name" => "Michal P.", "text" => "Šedá vypadá skvěle."),
    array("name" => "Filip G.", "text" => "Pohodlné i na cestách."),
    array("name" => "Jan Y.", "text" => "Moje doporučení."),
    array("name" => "Karel P.", "text" => "Drží tvar i pod košilí."),
    array("name" => "Matěj D.", "text" => "Styl bez námahy."),
    array("name" => "Emil C.", "text" => "Naprostá spokojenost.")
);
?>
