<?php
$auto_reviews_en = array(
    array("name" => "Jiří M.", "text" => "Barva boxerek zůstává stejná i po mnoha praních, nic nebledne."),
    array("name" => "Rostislav P.", "text" => "Boxerky Noriks mě opravdu překvapily. Materiál je měkký, nedráždí a netlačí tam, kde nemá."),
    array("name" => "Martin S.", "text" => "Opravdu pohodlné boxerky na celý den, skoro o nich nevím."),
    array("name" => "Tomáš R.", "text" => "Pružný pas je pevný, ale nestahuje. Nezařezává se do kůže."),
    array("name" => "Josef D.", "text" => "Prodyšné a lehké, ideální do práce i do fitka."),
    array("name" => "Lukáš M.", "text" => "Boxerky drží tvar i po opakovaném praní, nikde se nevytahují."),
    array("name" => "Kristián C.", "text" => "Materiál je hladký na kůži, žádné nepříjemné švy."),
    array("name" => "David V.", "text" => "I po celém dni nošení všechno drží na svém místě."),
    array("name" => "Michal L.", "text" => "Boxerky Noriks vypadají kvalitně hned na první dotek."),
    array("name" => "Petr G.", "text" => "Nosím je už týdny, žádné žmolky ani vytahání."),
    array("name" => "Antonín B.", "text" => "Perfektní střih – kopírují tělo, ale netlačí."),
    array("name" => "Filip J.", "text" => "Nohavice se nevyhrnují, což je pro mě obrovské plus."),
    array("name" => "Nikola R.", "text" => "Noriks boxerky jsou moje první volba v šuplíku."),
    array("name" => "Matěj S.", "text" => "Žádné nepříjemné pocení, materiál krásně dýchá."),
    array("name" => "Dominik K.", "text" => "Vypadají, že dlouho vydrží – švy jsou pevné a čisté."),
    array("name" => "Jan H.", "text" => "Skvělý poměr ceny a kvality, lepší než mnohem dražší značky."),
    array("name" => "Zbyněk P.", "text" => "Nevyhrnují se pod kalhotami, vše zůstává rovné."),
    array("name" => "Branislav N.", "text" => "Sedí perfektně, i když jsem mezi dvěma velikostmi."),
    array("name" => "René T.", "text" => "Pružný pas neztrácí elasticitu ani po více praních."),
    array("name" => "Andrej M.", "text" => "Ideální do práce i na trénink – jinou značku už nekupuji."),
    array("name" => "David K.", "text" => "Pocitově jako pyžamo, ale vypadají moderně."),
    array("name" => "Leon B.", "text" => "Pěkně tvarují bez pytlovitého vzhledu."),
    array("name" => "Darko Z.", "text" => "Materiál rychle schne, ideální na cestování."),
    array("name" => "Václav H.", "text" => "Netlačí ani při dlouhém sezení v kanceláři."),
    array("name" => "Karel F.", "text" => "Žádné tvrdé cedulky, všechno je precizně zpracované."),
    array("name" => "Tibor K.", "text" => "Nosím je celý den a večer jsou pořád pohodlné."),
    array("name" => "Boris V.", "text" => "Neotáčí se ani nekroutí pod džínami."),
    array("name" => "Mario Č.", "text" => "Střih pěkně kopíruje nohy a netvoří záhyby."),
    array("name" => "Štěpán C.", "text" => "Koupil jsem jedny a hned objednal další tři."),
    array("name" => "Radek N.", "text" => "Barva drží i u černých boxerek po mnoha praních."),
    array("name" => "Daniel L.", "text" => "Žádný zápach ani po náročném dni."),
    array("name" => "Goran B.", "text" => "Nahradily mi všechny staré boxerky."),
    array("name" => "Željko R.", "text" => "Nikde netlačí, ale zároveň dobře drží."),
    array("name" => "Vědran M.", "text" => "Ideální na léto, nelepí se na kůži."),
    array("name" => "Siniša J.", "text" => "Švy jsou hladké, žádné tření."),
    array("name" => "Vladimír N.", "text" => "Dostatečně pevné, ale pořád lehké."),
    array("name" => "Nino E.", "text" => "Drží vše na místě i při tréninku."),
    array("name" => "Saša K.", "text" => "Konečně spodní prádlo, které nedráždí."),
    array("name" => "Igor B.", "text" => "Ani po sušičce se nesrazily."),
    array("name" => "Janek T.", "text" => "Skvěle sedí i vyšším postavám."),
    array("name" => "Tvrtko G.", "text" => "Perfektní fit v pase i přes stehna."),
    array("name" => "Boris R.", "text" => "Tak pohodlné, že o nich skoro nevím."),
    array("name" => "Karel D.", "text" => "Do práce i do fitka – zvládnou všechno."),
    array("name" => "Milan H.", "text" => "Pas nezanechává stopy na kůži."),
    array("name" => "Zoran P.", "text" => "Příjemné na dotek, žádný umělý pocit."),
    array("name" => "Dušan K.", "text" => "První boxerky, které se mi nevyhrnují."),
    array("name" => "František M.", "text" => "Ideální poměr – ani úzké, ani široké."),
    array("name" => "Nikolas H.", "text" => "Nemusím je během dne upravovat."),
    array("name" => "Žarko V.", "text" => "Skvělé i na dlouhé cesty autem."),
    array("name" => "Marin J.", "text" => "Ani po měsíci praní neztrácí tvar."),
    array("name" => "Tonda P.", "text" => "Dobře sedí i pod oblekem."),
    array("name" => "Ondřej K.", "text" => "Od té doby nechci nosit jiné."),
    array("name" => "Lukáš B.", "text" => "Měkké, ale velmi odolné."),
    array("name" => "Karel Z.", "text" => "Bez podráždění i v horku."),
    array("name" => "Ladislav L.", "text" => "Nejpohodlnější boxerky, co jsem měl."),
    array("name" => "Viktor P.", "text" => "Ideální délka, nezařezávají se."),
    array("name" => "Damir G.", "text" => "Působí jako prémiová značka."),
    array("name" => "Alan S.", "text" => "Švy téměř necítím."),
    array("name" => "Kristián J.", "text" => "Nežmolkují a nechytají chlupy."),
    array("name" => "Lukáš F.", "text" => "Perfektní boxerky na každý den."),
    array("name" => "Mario R.", "text" => "I po tréninku všechno drží."),
    array("name" => "Antonín C.", "text" => "Příjemné překvapení – komfort 10/10."),
    array("name" => "Jan O.", "text" => "Koupil jsem více kusů a střídám jen je."),
    array("name" => "Štěpán V.", "text" => "Nevyhrnují se ani pod úzkými kalhotami."),
    array("name" => "David L.", "text" => "Materiál nezadržuje vlhkost."),
    array("name" => "Goran U.", "text" => "Skvělé pro lidi, co hodně sedí u počítače."),
    array("name" => "Mirek E.", "text" => "Po týdnech vypadají jako nové."),
    array("name" => "Bruno Č.", "text" => "Jednoduché, čisté, mužné."),
    array("name" => "Nikola K.", "text" => "Perfektní rovnováha pohodlí a opory."),
    array("name" => "Václav J.", "text" => "Nikde nezařezávají."),
    array("name" => "Srečko P.", "text" => "Snadná údržba a rychlé schnutí."),
    array("name" => "Leo M.", "text" => "Barvy odpovídají fotkám."),
    array("name" => "Damjan D.", "text" => "I v horku zůstávají pohodlné."),
    array("name" => "Dorian S.", "text" => "Neprosvítají pod tenkými kalhotami."),
    array("name" => "Adrian K.", "text" => "Široká guma se nekroutí."),
    array("name" => "René H.", "text" => "Cítím se v nich výrazně pohodlněji."),
    array("name" => "Zlatko R.", "text" => "Dobře střižené i pro silnější postavy."),
    array("name" => "Tomáš E.", "text" => "Bez problémů do práce i na trénink."),
    array("name" => "Karel L.", "text" => "Nemusím je pořád upravovat."),
    array("name" => "Nenad K.", "text" => "Velká spokojenost, beru další."),
    array("name" => "Dragan V.", "text" => "Nesjíždějí dolů, drží celý den."),
    array("name" => "Slavomír T.", "text" => "Perfektní tloušťka materiálu."),
    array("name" => "Alberto N.", "text" => "Skvělé i na cestování."),
    array("name" => "Zdeněk B.", "text" => "Po praní žádné deformace."),
    array("name" => "Ilja S.", "text" => "Netlačí v tříslech – konečně."),
    array("name" => "Mario L.", "text" => "Velmi pohodlné i při pohybu."),
    array("name" => "Lukáš Š.", "text" => "Nezařezávají se do boků."),
    array("name" => "Željko K.", "text" => "Tyhle boxerky si recenzi zaslouží."),
    array("name" => "Antonín Ž.", "text" => "Úplně nová úroveň pohodlí."),
    array("name" => "Vladimír R.", "text" => "Jakmile je zkusíš, jiné už nechceš."),
    array("name" => "Goran Č.", "text" => "Rychlé doručení, top produkt."),
    array("name" => "Vilém S.", "text" => "Perfektně sedí, nevyhrnují se."),
    array("name" => "Oleg T.", "text" => "Tak měkké, že je sotva cítím."),
    array("name" => "Štěpán I.", "text" => "Celý den bez jakéhokoli nepohodlí."),
    array("name" => "Karel H.", "text" => "Guma je výborná, neroluje se."),
    array("name" => "Darin P.", "text" => "Po praní stejné jako nové."),
    array("name" => "Adrian V.", "text" => "Skvělý materiál, prodyšný."),
    array("name" => "Leon M.", "text" => "Ideální délka, nic se nehýbe."),
    array("name" => "Augustin J.", "text" => "Moje první volba."),
    array("name" => "Kristián U.", "text" => "Žádné pocení ani po tréninku."),
    array("name" => "Dejan T.", "text" => "Předčilo očekávání."),
    array("name" => "Juraj A.", "text" => "Měkké, ale pevné."),
    array("name" => "Darko S.", "text" => "Nevlézají se do kalhot."),
    array("name" => "Benedikt K.", "text" => "Konečně boxerky, které netlačí."),
    array("name" => "Loren P.", "text" => "Velmi kvalitní materiál."),
    array("name" => "Ignác R.", "text" => "Kupují znovu."),
    array("name" => "Marin D.", "text" => "Velmi příjemné na kůži."),
    array("name" => "Miron B.", "text" => "Perfektně zpracované švy."),
    array("name" => "René M.", "text" => "Do kanceláře i do fitka."),
    array("name" => "Teodor Z.", "text" => "Jiné už nosit nechci."),
    array("name" => "Branislav Š.", "text" => "Pevná, ale pohodlná guma."),
    array("name" => "Valentin R.", "text" => "Nezadržují vlhkost."),
    array("name" => "Patrik L.", "text" => "Pohodlné i po hodinách nošení."),
    array("name" => "Tomáš U.", "text" => "Bez podráždění i v horku."),
    array("name" => "Mario Š.", "text" => "Velmi kvalitní zpracování."),
    array("name" => "Nikola D.", "text" => "Drží při cvičení."),
    array("name" => "Vít P.", "text" => "Po 10 praních jako nové."),
    array("name" => "Zdeněk T.", "text" => "Boxerky, které dávají smysl."),
    array("name" => "Lukáš K.", "text" => "Nedráždí pokožku."),
    array("name" => "Ernest B.", "text" => "Ideální na každý den."),
    array("name" => "Roman V.", "text" => "Pro mou postavu perfektní."),
    array("name" => "Marian G.", "text" => "Skvělé v létě i v zimě."),
    array("name" => "Kristof H.", "text" => "Nevypadají opotřebovaně ani po měsíci."),
    array("name" => "Tibor A.", "text" => "Střih mi sedí dokonale."),
    array("name" => "Fabian S.", "text" => "Pohodlné i při dlouhé jízdě."),
    array("name" => "Damjan K.", "text" => "Nejlepší boxerky, co jsem koupil."),
    array("name" => "Sebastian M.", "text" => "Prémiová kvalita materiálu."),
    array("name" => "Zoran U.", "text" => "Netlačí stehna."),
    array("name" => "Karel B.", "text" => "Drží vše na místě."),
    array("name" => "David P.", "text" => "Bez nepohodlí i po dlouhém dni."),
    array("name" => "Tin L.", "text" => "Ideální na každodenní nošení."),
    array("name" => "Ota R.", "text" => "Nevyhrnují se po celý den."),
    array("name" => "Slavko I.", "text" => "Špičkový komfort."),
    array("name" => "Janek S.", "text" => "Skvělá rovnováha pohodlí a opory."),
    array("name" => "Matěj V.", "text" => "Žádný klouzavý pocit."),
    array("name" => "Jan P.", "text" => "Drží tvar."),
    array("name" => "Julian D.", "text" => "Materiál je neuvěřitelně jemný."),
    array("name" => "Matouš H.", "text" => "Guma se neničí."),
    array("name" => "Vít Č.", "text" => "Kvalita lepší, než jsem čekal."),
    array("name" => "Bono K.", "text" => "Netušil jsem, že boxerky mohou být tak dobré."),
    array("name" => "Radek U.", "text" => "Skvělá ventilace."),
    array("name" => "Ladislav F.", "text" => "Bez tření i při dlouhé chůzi."),
    array("name" => "Michal T.", "text" => "Pohodlné i ve vedru."),
    array("name" => "Vilém P.", "text" => "Ideální pro mou postavu."),
    array("name" => "Ademir S.", "text" => "Materiál výborně dýchá."),
    array("name" => "Harun J.", "text" => "Velmi lehké a vzdušné."),
    array("name" => "Noah M.", "text" => "Drží barvu, neblednou."),
    array("name" => "Tomáš Č.", "text" => "Pohodlné i pod džínami."),
    array("name" => "Valentin L.", "text" => "Velmi příjemný pocit."),
    array("name" => "Dario S.", "text" => "Opravdu skvělé boxerky."),
    array("name" => "Leon N.", "text" => "Nosím je každý den."),
    array("name" => "Václav J.", "text" => "Bez záhybů a kroucení."),
    array("name" => "David P.", "text" => "Dostal jsem víc, než jsem čekal."),
    array("name" => "František S.", "text" => "Skvělé i na kolo."),
    array("name" => "Erik R.", "text" => "Rozhodně doporučuji."),
    array("name" => "Silvio M.", "text" => "Nežmolkují."),
    array("name" => "Zlatan G.", "text" => "Nevyhrnují se nahoru."),
    array("name" => "Dalibor S.", "text" => "Ideální pro citlivou pokožku."),
    array("name" => "Gorjan P.", "text" => "Guma nezanechává stopy."),
    array("name" => "Bohumil T.", "text" => "Maximální pohodlí."),
    array("name" => "Alan F.", "text" => "Totální game-changer."),
    array("name" => "Štěpán L.", "text" => "Rychle schnou."),
    array("name" => "Marek Ž.", "text" => "Nemačkají se pod kalhotami."),
    array("name" => "Vladimír Š.", "text" => "Žádný zápach ani po celém dni."),
    array("name" => "Lukáš R.", "text" => "Konečně boxerky, které drží."),
    array("name" => "Filip U.", "text" => "Snadná údržba."),
    array("name" => "Boris K.", "text" => "Měkké a velmi odolné."),
    array("name" => "Jan X.", "text" => "Nejlepší v této cenové třídě."),
    array("name" => "Bruno V.", "text" => "Opravdu se nevyhrnují."),
    array("name" => "Ondřej K.", "text" => "Velká spokojenost s materiálem."),
    array("name" => "Sandy B.", "text" => "Nedráždí pokožku."),
    array("name" => "Kevin S.", "text" => "Nosím je denně."),
    array("name" => "Matyáš P.", "text" => "Skvělý pocit při nošení."),
    array("name" => "Martin V.", "text" => "Po měsíci stále jako nové."),
    array("name" => "Oskar L.", "text" => "Pevné, ale pružné."),
    array("name" => "David J.", "text" => "Netlačí ani při cvičení."),
    array("name" => "Nikola U.", "text" => "Jednoduše perfektní."),
    array("name" => "Sven M.", "text" => "Guma se neroluje."),
    array("name" => "Robert P.", "text" => "Jedny z nejpohodlnějších boxerek."),
    array("name" => "Karel B.", "text" => "Rozhodně doporučuji."),
    array("name" => "Tomáš S.", "text" => "Materiál, který opravdu dýchá."),
    array("name" => "Radek K.", "text" => "Skvělé i na sport."),
    array("name" => "David Z.", "text" => "Nemám jedinou výtku."),
    array("name" => "Danilo F.", "text" => "Stojí za každou korunu."),
    array("name" => "Mirek K.", "text" => "Nosím je každý den."),
    array("name" => "Sebastian R.", "text" => "Bez chyby. Kupuji znovu.")
);
?>
